// Ambient declarations for compiled contract JSON files.
// The actual files are generated by `npm run build` in the repo root and
// resolved at bundle time via the @contracts Vite alias (→ ../build/).
// These declarations give TypeScript the correct shape without needing the
// files to exist during `tsc --noEmit`.

declare module "@contracts/*.compiled.json" {
  const value: { hex: string };
  export default value;
}
